const listas = [
	{
		codigo: 1,
		descripcion: "FRAM",
		mes2: "Enero",
		mes: "Ultima Actualización:",
		aumento: "(El aumento fue 5% lineal) ",
		descuento: "Consultar descuento x cantidad",
	},
	{
		codigo: 12,
		descripcion: "MOTUL",
		mes2: "Febrero",
		mes: "Ultima Actualización:",
		aumento: "(El aumento fue 9% lineal)",
		descuento: "",
	},
	{
		codigo: 3,
		descripcion: "VALVOLINE",
		mes2: "Febrero",
		mes: "Ultima Actualización:",
		aumento: "(El aumentto fue: 6% promedio)",
		descuento: "",
	},
	{
		codigo: 316,
		descripcion: "PETRONAS",
		mes2: "Diciembre",
		mes: "Ultima Actualización:",
		aumento: "(El aumentto fue: 7% promedio)",
		descuento: "",
	},
	// {"codigo":5,    "descripcion":"TOTAL",          "mes2":"Abril", "mes":"Ultima Actualización:",   "aumento":"(El aumento fue: 10%)",                "descuento":""},
	// {
	// 	codigo: 27,
	// 	descripcion: "PUMA",
	// 	mes2: "Junio",
	// 	mes: "Ultima Actualización:",
	// 	aumento: "(El aumento fue: desparejo)",
	// 	descuento: "",
	// },
	{
		codigo: 14,
		descripcion: "LOCX",
		mes2: "Noviembre",
		mes: "Ultima Actualización:",
		aumento: "(El aumento fue: 6%)",
		descuento: "",
	},
	{
		codigo: 11,
		descripcion: "WAGNER LOCKHEED",
		mes2: "Noviembre",
		mes: "Ultima Actualización:",
		aumento: "(El aumento fue: 12%) ",
		descuento: "",
	},
	{
		codigo: 8,
		descripcion: "RAMA",
		mes2: "Diciembre",
		mes: "Ultima Actualización:",
		aumento: "(El aumento fue hasta: 8%)",
		descuento: "",
	},
];

module.exports = {
	listas: listas,
};
