const listas = [
	{
		codigo: 1,
		descripcion: "FRAM",
		mes2: "04 de Febrero",
		mes: "Ultima Actualización:",
		aumento: " 10% ",
		descuento: "Consultar descuento x cantidad",
	},
	{
		codigo: 12,
		descripcion: "MOTUL",
		mes2: "01 de Febrero",
		mes: "Ultima Actualización",
		aumento: "12%",
		descuento: "",
	},
	{
		codigo: 3,
		descripcion: "VALVOLINE",
		mes2: "15 de Diciembre",
		mes: "Ultima Actualización:",
		aumento: "60%",
		descuento: "",
	},
	{
		codigo: 316,
		descripcion: "PETRONAS",
		mes2: "06 de Febrero",
		mes: "Ultima Actualización:",
		aumento: "Hasta un 5%",
		descuento: "",
	},
	{
		codigo: 5,
		descripcion: "TOTAL",
		mes2: "15 de Diciembre",
		mes: "Ultima Actualización:",
		aumento: "60%",
		descuento: "",
	},
	{
		codigo: 14,
		descripcion: "LOCX",
		mes2: "15 de Diciembre",
		mes: "Ultima Actualización:",
		aumento: "40%",
		descuento: "",
	},
	{
		codigo: 27,
		descripcion: "PUMA",
		mes2: "15 de Diciembre",
		mes: "Ultima Actualización:",
		aumento: "55%",
		descuento: "",
	},
	{
		codigo: 8,
		descripcion: "RAMA",
		mes2: "1 de Diciembre",
		mes: "Ultima Actualización:",
		aumento: "17%",
		descuento: "",
	},
];

module.exports = {
	listas: listas,
};
