const listas = [
	{
		codigo: 1,
		descripcion: "FRAM",
		mes2: "AGOSTO",
		mes: "Lista Vigente:",
		aumento: "Ultima actualización JUNIO: 6% lineal",
		descuento: "Consultar descuento x cantidad",
	},
	{
		codigo: 12,
		descripcion: "MOTUL",
		mes2: "AGOSTO",
		mes: "Lista Vigente:",
		aumento: "Ultima actualización JULIO: 5% lineal",
		descuento: "",
	},
	{
		codigo: 3,
		descripcion: "VALVOLINE",
		mes2: "AGOSTO",
		mes: "Lista Vigente:",
		aumento: "Ultima actualización JULIO: 5% lineal",
		descuento: "",
	},
	// {
	// 	codigo: 316,
	// 	descripcion: "PETRONAS",
	// 	mes2: "10 de Junio",
	// 	mes: "Ultima Actualización:",
	// 	aumento: "Subas y bajas desaprejas",
	// 	descuento: "",
	// },
	{
		codigo: 5,
		descripcion: "TOTAL",
		mes2: "AGOSTO",
		mes: "Lista Vigente:",
		aumento: "",
		descuento: "",
	},
	{
		codigo: 14,
		descripcion: "LOCX",
		mes2: "AGOSTO",
		mes: "Lista Vigente:",
		aumento: "Ultima actualización AGOSTO: desparejo",
		descuento: "",
	},
	{
		codigo: 27,
		descripcion: "PUMA",
		mes2: "AGOSTO",
		mes: "Lista Vigente:",
		aumento: "Ultima actualización JULIO: 4% NO lineal",
		descuento: "",
	},
	{
		codigo: 8,
		descripcion: "RAMA",
		mes2: "AGOSTO",
		mes: "Lista Vigente:",
		aumento: "Ultima actualización AGOSTO: 10% NO lineal",
		descuento: "",
	},
];

module.exports = {
	listas: listas,
};
